embedding_size: 768
hidden_size: 128
model_path: models/
batch_size: 128
max_length: 128
dropout: 0.5
tags:
  - NFG
  - TIME
  - NSS
  - NGL
  - PER
  - LOC
  - NFG
  - PER
  - NWZ
  - NWZ
  - ORG
  - NGL
  - TIME
  - NJZ
  - LOC
  - ORG
  - NSS
  - NJZ